version: '3.9'
# Official images from the zabbix repository were used as a base, as there is no need for any changes to the images.
# The few that are needed are possible to do behind variables that can be passed in the creation of the container.
networks:
  network-zabbix:
    driver: bridge 

# -- End netowork configuration. --

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    networks:
      - network-zabbix
    ports:
      - '3306:3306'
    volumes:
      - './zabbix/mysql:/var/lib/data'
    environment:
      - MYSQL_ROOT_PASSWORD=urzedo
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=urzedo

# -- End MySQL configuration. --

  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-mysql:ubuntu-5.0.1
    networks:
      - network-zabbix
    links:
      - mysql
    restart: always
    ports:
      - '10051:10051'
    volumes:
      - './zabbix/alertscripts:/usr/lib/zabbix/alertscripts'
    environment:
      - DB_SERVER_HOST=mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=urzedo
    depends_on:
      - mysql

# -- End Zabbix Server configuration. --

  zabbix-frontend:
    container_name: zabbix-frontend
    image: zabbix/zabbix-web-apache-mysql:ubuntu-5.0.1
    networks:
      - network-zabbix
    links:
      - mysql
    restart: always
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - DB_SERVER_HOST=mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=urzedo
      - PHP_TZ=America/Sao_Paulo # Example of an important native Zabbix variable that changes the timezone settings of Zabbix and php files to get the correct time in Brazil.
    depends_on:
      - mysql

# -- End Web Server of Zabbix configuration. --
   
  grafana:
    container_name: grafana
    image: grafana/grafana
    networks:
      - network-zabbix
    links:
      - mysql
      - zabbix-server
    restart: always
    ports:
      - '3000:3000'
    environment: 
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
    depends_on:
      - mysql
      - zabbix-server

# Grafana is an Open Source measurement visualization and analysis suite, used in different markets for real-time data visualization.
# -- End Grafana Server configuration. --

  zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent2:alpine-5.0.1
    user: root
    networks:
      - network-zabbix
    links:
      - zabbix-server
    restart: always
    privileged: true
    volumes:
      - /var/run:/var/run
    ports:
      - '10050:10050'
    environment:
      - ZBX_HOSTNAME=Zabbix server
      - ZBX_SERVER_HOST=172.18.0.1

# Zabbix agent is necessary for the server to collect all its information and present it on the platform, thus having a control of the resources and etc of the zabbix server itself.
# -- End Zabbix Agent configuration. --
    